chore: release

diff --git a/dev/bin/release-new-version b/dev/bin/release-new-version
--- a/dev/bin/release-new-version
+++ b/dev/bin/release-new-version
@@ -3,14 +3,14 @@
 # This script releases a new version of the project.
 
 function get-version
-    stack run findata-funnel -- --version
+    cabal run -v0 findata-funnel -- --version
+    or begin
+        echo "Could not get the current version. Aborting."
+        exit 1
+    end
 end
 
 set OLD_VERSION (get-version)
-or begin
-    echo "Could not get the current version. Aborting."
-    exit 0
-end
 
 echo "Bump up the new version in package.yaml. Once done, confirm [y/n]":
 read confirm
@@ -21,15 +21,16 @@ switch $confirm
         echo "Aborting due to lack of confirmation (user input was $confirm)."
         exit 0
 end
-set NEW_VERSION (get-version)
-and echo "New version: $NEW_VERSION."
-git add package.yaml
-and echo "Rebuilding to update findata-funnel.cabal."
-and stack build
+and echo "Old version: $OLD_VERSION."
+and git add package.yaml
+and echo "Updating findata-funnel.cabal…"
+and hpack
 and git add findata-funnel.cabal
-and echo "Committing the new version."
+and set NEW_VERSION (get-version)
+and echo "New version: $NEW_VERSION."
+and echo "Committing the new version…"
 and git commit -m 'chore: release'
 and git push
-and echo "Tagging the new version."
+and echo "Tagging the new version ($NEW_VERSION)…"
 and git tag v$NEW_VERSION
 and git push origin v$NEW_VERSION
